name: Node Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 17
      - run: npm ci
      - run: npm run build_app_macOS